name: New University

on:
  issues:
    types: [opened, edited]

permissions:
  pull-requests: write
  contents: write

jobs:
  autopr:
    if: ${{ startsWith(github.event.issue.title, '[New University]') }}
    runs-on: ubuntu-latest
    env:
      USER_NAME: ${{ github.event.issue.user.login }}
      USER_ID: ${{ github.event.issue.user.id }}
      ISSUE_ID: ${{ github.event.issue.id }}
    steps:
      - uses: actions/checkout@v4
      - uses: stefanbuck/github-issue-parser@v3
        id: issue
        with:
          template-path: .github/ISSUE_TEMPLATE/uninew.yml

      - name: Set environment variables
        env:
          TMP_UNI_NAME: ${{ steps.issue.outputs.issueparser_name }}
        run: echo "UNI_NAME=$TMP_UNI_NAME" >> $GITHUB_ENV

      - name: Insert university into database
        uses: sanjacob/json-insert@v1
        env:
          UNI_NAME: ${{ steps.issue.outputs.issueparser_name }}
          UNI_SHORT_NAME: ${{ steps.issue.outputs.issueparser_short-name }}
          UNI_START_URL: ${{ steps.issue.outputs.issueparser_login-start-url }}
          UNI_TARGET_URL: ${{ steps.issue.outputs.issueparser_login-target-url }}
        with:
          file: blackboard_sync/universities.json
          index: -2
          item: |
            {
              "name": "${{ env.UNI_NAME }}",
              "short_name": "${{ env.UNI_SHORT_NAME }}",
              "login": {
                "start_url": "${{ env.UNI_START_URL }}",
                "target_url": "${{ env.UNI_TARGET_URL }}"
              },
              "api_url": "${{ env.UNI_START_URL }}"
            }

      - name: Find country information
        uses: sanjacob/country-iso@v2
        id: country
        env:
          COUNTRY: ${{ steps.issue.outputs.issueparser_country }}
        with:
          name: ${{ env.COUNTRY }}

      - name: Map country code to country section
        uses: kanga333/variable-mapper@c140b458cb69bd8c9c5eccd41e83aadc597c1352
        id: header
        with:
          key: "${{ steps.country.outputs.name }}"
          map: |
            {
              "MX": { "section": "Mexico" },
              "NZ": { "section": "New Zealand" },
              "CA": { "section": "Canada" },
              "US": { "section": "United States of America" },
              "GB": { "section": "England" },
              ".*": { "section": "" }
            }
          export_to: output

      - name: Map country code to continent section
        if: ${{ steps.header.outputs.section == '' }}
        uses: kanga333/variable-mapper@c140b458cb69bd8c9c5eccd41e83aadc597c1352
        id: header-b
        with:
          key: "${{ steps.country.outputs.continent }}"
          map: |
            {
              "AF": { "section": "Africa" },
              "AS": { "section": "Asia" },
              "EU": { "section": "Rest of Europe" },
              "NA": { "section": "United States of America" },
              "OC": { "section": "Australia" },
              "SA": { "section": "South America" },
              ".*": { "section": "Not Found" }
            }
          export_to: output

      - name: Append university to UNIVERSITIES
        uses: sanjacob/markdown-list@v1
        env:
          HEADER_A: ${{ steps.header.outputs.section }}
          HEADER_B: ${{ steps.header-b.outputs.section }}
        with:
          file: "UNIVERSITIES.md"
          header: ${{ env.HEADER_A || env.HEADER_B }}
          item: ${{ env.UNI_NAME }}

      - name: Add entry to CHANGELOG
        uses: sanjacob/markdown-list@v1
        with:
          file: "CHANGELOG.md"
          header: Added
          item: >
            Add support for ${{ env.UNI_NAME }} (${{ env.USER_NAME }})

      - name: Create new branch
        run: |
          git switch -c "uni-$ISSUE_ID"

      - name: Set GitHub commit author
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Create commit
        run: |
          git add .
          USER_EMAIL="${USER_ID}+${USER_NAME}@noreply.users.github.com"
          git commit -m "Add support for $UNI_NAME

          Co-authored-by: $USER_NAME <$USER_EMAIL>"

      - name: Push new branch to origin
        run: git push origin "uni-$ISSUE_ID"

      - name: Create pull request
        run: >
          gh pr create -B main -H "uni-$ISSUE_ID"
          --title "Add support for $UNI_NAME"
          --body "Created on behalf of $USER_NAME"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
